<?php

namespace EntitiesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EnchereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnchereRepository extends EntityRepository
{
}
