<?php

namespace EntitiesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TchatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TchatRepository extends EntityRepository
{
}
