EntitiesBundle\Entity\Enchere:
    type: entity
    table: null
    repositoryClass: EntitiesBundle\Repository\EnchereRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idUser:
            type: integer
        idArticle:
            type: integer
        newPrice:
            type: integer
        date:
            type: date
    lifecycleCallbacks: {  }
