user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

entities:
    resource: "@EntitiesBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
